### ISSUE TITLE
Elasticsearch & MongoDB Authentication & Access to External Internet

### ISSUE THREAD

**Issue by rhrpr** [beatcracker/rancher-graylog#4]
I host a server in Germany and was notified by the German Federal Office for Information Security (BSI) of the following;

> Elasticsearch is a popular search engine based on Apache Lucene,
> often used with web applications.
> 
> If an Elasticsearch server is openly accessible from the Internet
> and not protected by any forms of authentification, anyone who can
> connect to the server has unrestricted access to the data stored
> with it. This allows attackers to modify or delete any data or
> potentially steal sensitive information. In addition, prior to
> versions 1.2.x an attacker can use dynamic scripting to perform
> arbitrary code execution on the machine that Elasticsearch is
> hosted on.

Can we add authentication & internal NW constraints to the compose file? 
I might have time to submit a PR later today

**Comment by rhrpr** [comment]
I was notified of the same for MongoDB

> MongoDB is a popular NoSQL database system commonly used as a backend
> for web applications. Access to a MongoDB server should be restricted
> to trusted systems (for example, the related web application server).
> If a MongoDB server is openly accessible from the Internet, an attacker
> can take advantage of this to access the server and modify or delete
> data, or even obtain sensitive information like customer data from
> an online shop.

**Comment by beatcracker** [comment]
Yep, both MongoDB an Elasticsearch are used w/o auth here. I'm reluctant to add it, since this repo is supposed to be quick and dirty way to spin up Graylog instance for testing/poking around.

For example, downloading plugins during startup is no-go for production, they should be baked in in the docker image, you need clustering for elasticsearch and so on...

Perhaps implementing #2 will suffice, since this way elasticsearch/mongo will be only available inside the Rancher network (which can be hardened using [network policies](http://rancher.com/docs/rancher/v1.6/en/rancher-services/network-policy/)).

**Comment by stieler-it** [comment]
This is a duplicate of #2 which I opened for the exact same reason. A default password should not be a problem when the port is not routable from public network.

**Comment by beatcracker** [comment]
Closing since #2 is fixed.
